blueprint:
  name: "Philips Hue Dimmer Switch: Bedroom v13"
  description: "Control a bedside lamp, a ceiling light, and turn off other lights in the bedroom with the Philips Hue Dimmer Switch."
  domain: automation
  input:
    remote:
      name: "Philips Hue Dimmer Switch"
      selector:
        device:
          filter:
            - integration: "zha"
              manufacturer: "Signify Netherlands B.V."
              model: "RWL022"
          multiple: false
    bedside_lamp:
      name: Bedside Lamp
      description: The bedside lamp to control
      selector:
        target:
          entity:
            - domain:
                - light
    ceiling_light:
      name: Ceiling light
      description: Ceiling light in the room
      selector:
        target:
          entity:
            - integration: zha
    other_lights:
      name: Other lights
      description: Other lights in the room
      selector:
        target:
          entity:
            - integration: zha
  source_url: https://github.com/urbas/ha-philips-dimmer-switch/blob/master/ha-philips-dimmer-switch-blueprint.yaml
mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
action:
  # https://www.home-assistant.io/docs/scripts/#variables
  # https://www.home-assistant.io/docs/blueprint/schema/#blueprint-inputs-in-templates
  - variables:
      command: "{{ trigger.event.data.command }}"
      # bedside_lamp.device_id
      bedside_lamp: !input bedside_lamp
  - choose:
      # Toggle on/off
      - conditions:
          - "{{ command == 'on_press' }}"
        sequence:
          - action: light.toggle
            target: !input bedside_lamp

      # Turn on to minimum brightness
      - conditions:
          - "{{ command == 'on_hold' }}"
        sequence:
          - service: light.turn_on
            target: !input bedside_lamp
            data:
              brightness_pct: 1
              transition: 1

      # Brightness up
      - conditions:
          - "{{ command == 'up_hold' }}"
        sequence:
          - service: light.turn_on
            target: !input bedside_lamp
            data:
              brightness_step_pct: 20
              transition: 1
      - conditions:
          - "{{ command == 'up_short_release' }}"
        sequence:
          - service: light.turn_on
            target: !input bedside_lamp
            data:
              brightness_step_pct: 5
              transition: 0

      # Brightness down
      - conditions:
          - "{{ command == 'down_hold' }}"
        sequence:
          - service: light.turn_on
            target: !input bedside_lamp
            data:
              brightness_step_pct: -20
              transition: 1
      - conditions:
          - "{{ command == 'down_short_release' }}"
        sequence:
          - service: light.turn_on
            target: !input bedside_lamp
            data:
              brightness_step_pct: -5
              transition: 0

      # Toggle ceiling lights on
      - conditions:
          - "{{ command == 'on_double_press' }}"
        sequence:
          - service: homeassistant.toggle
            target: !input ceiling_light
            data: {}

      # Turn everything off
      - conditions:
          - "{{ command == 'off_press' }}"
        sequence:
          - service: homeassistant.turn_off
            target: !input bedside_lamp
            data: {}
          - service: homeassistant.turn_off
            target: !input other_lights
            data: {}
          - service: homeassistant.turn_off
            target: !input ceiling_light
            data: {}
