blueprint:
  name: "ZHA - Philips Hue Dimmer Switch"
  description: "Control a dimmable light with a Philips Hue Dimmer Switch."
  domain: automation
  input:
    remote:
      name: "Philips Hue Dimmer Switch"
      selector:
        device:
          filter:
            - integration: "zha"
              manufacturer: "Signify Netherlands B.V."
              model: "RWL022"
          multiple: false
    light:
      name: Light(s)
      description: The light(s) to control
      selector:
        target:
          entity:
            - domain:
                - light
  source_url: https://github.com/urbas/ha-philips-dimmer-switch/blob/master/ha-philips-dimmer-switch-blueprint.yaml
mode: restart
max_exceeded: silent
variables:
  force_brightness: !input force_brightness
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
action:
  - variables:
      command: "{{ trigger.event.data.command }}"
  - choose:
      # Toggle light on and off
      - conditions:
          - "{{ command == 'on_short_release' }}"
        sequence:
          - service: light.toggle
            target: !input light
            data:
              transition: 1
