blueprint:
  name: "Philips Hue Dimmer Switch v9"
  description: "Control a dimmable light with a Philips Hue Dimmer Switch."
  domain: automation
  input:
    remote:
      name: "Philips Hue Dimmer Switch"
      selector:
        device:
          filter:
            - integration: "zha"
              manufacturer: "Signify Netherlands B.V."
              model: "RWL022"
          multiple: false
    bedside_lamp:
      name: Bedside Lamp
      description: The bedside lamp to control
      selector:
        target:
          entity:
            - domain:
                - light
    other_lights:
      name: Other lights
      description: Other lights in the room
  source_url: https://github.com/urbas/ha-philips-dimmer-switch/blob/master/ha-philips-dimmer-switch-blueprint.yaml
mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
action:
  - variables:
      command: "{{ trigger.event.data.command }}"
  - choose:
      # Toggle on/off
      - conditions:
          - "{{ command == 'on_press' }}"
        sequence:
          - service: light.toggle
            target: !input bedside_lamp
            data: {}

      # Turn on to minimum brightness
      - conditions:
          - "{{ command == 'on_hold' }}"
        sequence:
          - service: light.turn_on
            target: !input bedside_lamp
            data:
              brightness_pct: 1
              transition: 1

      # Brightness up
      - conditions:
          - "{{ command == 'up_hold' }}"
        sequence:
          - service: light.turn_on
            target: !input bedside_lamp
            data:
              brightness_step_pct: 20
              transition: 1
      - conditions:
          - "{{ command == 'up_short_release' }}"
        sequence:
          - service: light.turn_on
            target: !input bedside_lamp
            data:
              brightness_step_pct: 5
              transition: 0

      # Brightness down
      - conditions:
          - "{{ command == 'down_hold' }}"
        sequence:
          - service: light.turn_on
            target: !input bedside_lamp
            data:
              brightness_step_pct: -20
              transition: 1
      - conditions:
          - "{{ command == 'down_short_release' }}"
        sequence:
          - service: light.turn_on
            target: !input bedside_lamp
            data:
              brightness_step_pct: -5
              transition: 0

      # Turn everything off
      - conditions:
          - "{{ command == 'on_triple_press' }}"
        sequence:
          - service: homeassistant.turn_off
            target: !input bedside_lamp
            data: {}
          - service: homeassistant.turn_off
            target: !input other_lights
            data: {}
